### PR TITLE
Remove denver directory and update chapter GitHub URL

### PR DESCRIPTION
**Pull request by nateirwin**
We are migrating the MaptimeMileHigh website into its own GitHub repository (which @lyzidiamond  created for us - thanks!). This pull request removes the `/denver` directory and updates the URL in chapters.json to point to our new GitHub repository.

Once this request is merged, I will change the name of our "milehigh" repository to "denver" and we should be good to go.

Thanks!

### CODE REVIEW

**Comment by nateirwin** [comment]
Any chance we can this merged @lyzidiamond or @geografa? Thanks!

**Comment by svmatthews** [comment]
Hey @nateirwin! The `title` hasn't been updated in the `chapters.json` file. I assume it should change to "Denver"? Are you going to be running a new twitter at all?

**Comment by nateirwin** [comment]
Hi, @svmatthews. Sorry about the delay getting back to you on this!

I believe we are going to keep the title "MaptimeMileHigh", so I cleaned up the chapters.json file. Thanks for pointing out the problem; I was in a hurry, and missed a few things.

**Comment by nateirwin** [comment]
Any chance we can get this merged now, @svmatthews?

Thanks!

**Comment by svmatthews** [comment]
:zap: :boom: :facepunch:

**Comment by nateirwin** [comment]
Thanks!

**Pull request merged**
