### PR TITLE
Updated Campinas chapter

### PR DESCRIPTION
**Pull request by tamielbr**
Noticed there was a  "Null Island" in the middle of the json file that should probably be removed.

### CODE REVIEW

**Comment by svmatthews** [comment]
But null island IS a maptime chapter! https://twitter.com/maptimenull

**Comment by geobrando** [comment]
http://www.nullisland.com/ :smile:

**Comment by tamielbr** [comment]
I just joined, and the things I learn! ;)

**Comment by geobrando** [comment]
Hey @tamielbr 

Have you started having events? If not, we should add a `"comingSoon": true` tag.

Also, let me know if you or your co-organizer need to be added to our Slack.

Thanks

**Comment by tamielbr** [comment]
He are trying to find a common time with some OSM folks. Should be early in June for our inaugural event. I can switch comingSoon.

**Comment by geobrando** [comment]
@tamielbr If you're planning something for that soon then don't worry about adding the tag.

**Comment by tamielbr** [comment]
Sounds good. We'll keep y'all posted.

**Comment by geobrando** [comment]
Good luck!

Since this PR is so stale now it's causing a conflict.  Looks like you made some minor changes.  Current version looks fine to me but if you would like for these changes to be made I'll have to fix it or ask that you submit another pull request.

**Pull request closed without merging**
