### PR TITLE
Onboarding form

### PR DESCRIPTION
**Pull request by svmatthews**
**Don't merge this!!** This is all related to maptime/maptime-admin/issues/48 and is a WIP.

Adding a new `<form>` that sends info to the Formspree servers, and then emails the info to an email address specified in the form code. The redirect goes to `/start/?submit=true#start-form` which fires the `start.js` file to add a new alert to the page showing that the submission was successful. It also goes to the anchor `#start-form` to make it a better user experience.

This functionality is only the HTML form, and should probably be added to the work necessary for #153 before being merged in since `/start` isn't the final URL.

Things to be finalized:

- [ ] form fields and content (include note that info will be made public)
- [ ] success message
- [ ] `/start` page content - see #153 
- [ ] update form to send to `??????@maptime.io`
- [ ] "reply to" email address?
- [ ] Email subject

### Form Content

* name
* email
* personal twitter handle (optional)
* Where do you want to start a Maptime?
* When do you want to start?
* Why do you want to start a Maptime?
* Chapter twitter handle
* Organizer GH handle
* Additional organizer names (optional)

### CODE REVIEW

**Comment by svmatthews** [comment]
Some screenshots of the form

**Blank:**
screen shot 2015-04-23 at 6 04 37 pm

**Submitted:**
screen shot 2015-04-23 at 6 08 51 pm

**Comment by bethschechter** [comment]
My god i love you guys.

//typed with thumbs

**Comment by geografa** [comment]
:heart:

**Comment by geografa** [comment]
Quick check here - we're foregoing the _Create an issue in the Starter repo_ in lieu of the form?

**Comment by svmatthews** [comment]
Good question! Honestly unsure, and have no particular opinion either way since you're the ones doing the heavy lifting.

**Comment by geografa** [comment]
@svmatthews Ok. Cool, done for now. lmk how the copy reads. Form would have to change based on some of that text (like requiring GH user) but we can flexible for sure. We use forms internally to track things like [Drone Feedback](https://github.com/mapbox/drone-feedback) so that's doable down the road.

**Comment by svmatthews** [comment]
Neat! :airplane: Does that use a server?

**Comment by geografa** [comment]
@tristen might know about this. Drone feedback form to Github issues?

**Comment by tristen** [comment]
@svmatthews I :+1: recommend using [Zapier](https://zapier.com/) for this. It's a webhook service that offers a free service to cover basic needs. You can set something up like:

- User submits online form powered by Google docs
- Zapier listens for the submission and pipes the output into a GitHub issue

Used this for a couple things and it's great!

**Comment by svmatthews** [comment]
Ohh @tristen thanks for sharing this! That's neat - pretty much like an IFTTT equivalent?

I think it's possible to connect gmail to listen for incoming emails from Formspree and then push as a github issue - therefore removing the dependency on Google forms (which allows us to nicely integrate a form into the website).

**Comment by tristen** [comment]
>  pretty much like an IFTTT equivalent?

Pretty much. Zapier get's a little more granular with the services they support. Output to a github issue can be very specific.

**Comment by geobrando** [comment]
This is great.  If we're pushing these as github issues though it should be made clear in the form that any information they provide will be made public, unless HQ is thinking about a private repo.

**Comment by svmatthews** [comment]
Good point, @geobrando! Added a note to the list at the top.

**Comment by geografa** [comment]
While you're thinking of forms and Zapier, may be good to survey these:
https://zapier.com/blog/best-online-form-builder-software/

**Comment by geobrando** [comment]
@svmatthews Hmm.. what about instead of pushing the raw form data as an issue you just push the "Where" and the "When" (as an indicator of urgency. You could probably even apply an issue tag if you made it a drop down box).  Then HQ could go back and find the email with the particulars.

**Comment by geobrando** [comment]
Formspree sounds really cool. But if the approach I mentioned above is desired, you could put a google form in an iframe, right?  Then you could probably push the url of the completed form to github and make it private so only certain people could access it. Or is that crazy?

**Comment by svmatthews** [comment]
Truth! But that would require a private account :disappointed:

**Comment by geografa** [comment]
What are privacy concerns here? if so, users can just email, right?

**Comment by geobrando** [comment]
@geografa For sure, but you're using github issues as a way to manage chapter requests since there's more than one of you responsible for that.  That way there's a "paper trail" for everyone to know where you are in the process.  My sense was that you (or @bethschechter specifically) were trying to automate/streamline this as much as possible.  Point being, you could use github as a way to manage requests and still have some private communications (like email address and the "Why do you want to start a maptime").  I know I would fill weird about writing that if I knew it was going to be displayed publicly.

**Comment by bethschechter** [comment]
I didn't even think about privacy in this instance. It's more about just
making sure that there's a database of everyone who has reached out, and a
clear way for onboarding volunteers to track their status of adding people
to Slack / GH, etc.

Hello@maptime.io should always be an option for people who have questions /
are allergic to forms / etc.

On Fri, Apr 24, 2015 at 3:05 PM, Brandon Knight <notifications@github.com>
wrote:

> @geografa <https://github.com/geografa> For sure, but you're using github
> issues as a way to manage chapter requests since there's more than one of
> you responsible for that. That way there's a "paper trail" for everyone to
> know where you are in the process. My sense was that you (or
> @bethschechter <https://github.com/bethschechter> specifically) were
> trying to automate/streamline this as much as possible. Point being, you
> could use github as a way to manage requests and still have some private
> communications (like email address and the "Why do you want to start a
> maptime"). I know I would fill weird about writing that if I knew it was
> going to be displayed publicly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maptime/maptime.github.io/pull/177#issuecomment-96079896>
> .
>



-- 
@bethschechter
Maptime <http://maptime.io/> founder
ATL –> SF –> PDX

**Comment by geografa** [comment]
I'm sure there's a way to control what does and doesn't get pushed to the GH issue. It seems like we don't even need a email for this form. If we get their GH username, they get added to a team and they have to accept before we make the repo.

**Comment by bethschechter** [comment]
Oh! i just had a moment of clarity around what you were saying: instead of
pushing a notification of submission to hello@, it would get pushed to an
issue. gotcha.

I want for @lyzidiamond to weigh in on this, as issues sometimes get lost
in the fray. Lyzi, would you prefer to have an email notification or a GH
notification??

On Fri, Apr 24, 2015 at 3:24 PM, geografa <notifications@github.com> wrote:

> I'm sure there's a way to control what does and doesn't get pushed to the
> GH issue. It seems like we don't even need a email for this form. If we get
> their GH username, they get added to a team and they have to accept before
> we make the repo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maptime/maptime.github.io/pull/177#issuecomment-96082125>
> .
>



-- 
@bethschechter
Maptime <http://maptime.io/> founder
ATL –> SF –> PDX

**Comment by geobrando** [comment]
I think this all comes down to how much automation you think you'll need, how many volunteers will be responsible for onboarding, and if you want to use github issues to manage the process.  That will decide how much use use hello@ for this and what kind of form you want.

**Comment by bethschechter** [comment]
Totally. Lyzi is interested in taking the lead on this, so that's why I
want to see what works best for her. Thanks!

On Fri, Apr 24, 2015 at 3:31 PM, Brandon Knight <notifications@github.com>
wrote:

> I think this all comes down to how much automation you think you'll need,
> how many volunteers will be responsible for onboarding, and if you want to
> use github issues to manage the process. That will decide how much use use
> hello@ for this and what kind of form you want.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maptime/maptime.github.io/pull/177#issuecomment-96084770>
> .
>



-- 
@bethschechter
Maptime <http://maptime.io/> founder
ATL –> SF –> PDX

**Comment by lyzidiamond** [comment]
Thoughts (voicing with @svmatthews):

- Making it a GitHub issue is good for keeping things in one spot (email sucks for this)
- Making it a GitHub issue will make continued conversation between HQ and the new organizer difficult if the new organizer doesn't know anything about GitHub
- COUNTERPOINT: they have to use GitHub to set up their chapter website anyway, so the friction will be created at a certain point anyway
- POTENTIAL SOLUTION: have awesome "WTF GitHub" guidance from the get-go
- Potential snag: someone isn't sure they want to start a chapter -- do they fill out the form?
  - piggyback from Sam: if the friction exists as learning GitHub, will they lose interest more quickly because the barrier is too close to point of entry?
- Lyzi thought: GitHub knowledge should not be a measuring stick for starting a chapter. That's antithetical to our whole mission.
- Another thought: adding to twitter list, slack, making a github repo -- these things don't take a long time but they do when nobody is explicitly doing them. So these tasks should be delegated specifically to one person of a small group of people.

Discuss more and I'll think more and make a decision by end of day.

**Comment by geobrando** [comment]
A few thoughts:

* We should have a low barrier for people to participate in Maptime events, but requiring that organizers of a group focused on technology be able to sign up for a Github account and use Github issues is reasonable.  HQ can help get them set up with the website, and it's up to organizers if they want to learn how to manage it by making commits, submitting pull requests, etc  We've talked before about tools like Prose.io that might help them become acclimated and your idea about directing them to learning resources from the start is a good one.

* The form should be for those with a genuine interest in starting a chapter.  Any other questions about maptime should be directed to hello@maptime.io

>Another thought: adding to twitter list, slack, making a github repo -- these things don't take a long time but they do when nobody is explicitly doing them. So these tasks should be delegated specifically to one person of a small group of people.

* Agreed. If every chapter request has its own issue, someone can be assigned and is thus responsible for the above.  Much harder to coordinate by keeping track of an email.

I don't know how form data is delivered with Formspree, but if you wanted to go the automated github route there might be better options.

**Comment by geografa** [comment]
My personal fave is [Typeform](http://www.typeform.com/). Ties in nicely with GH through Zapier. Lots of control over form design and tracks items for you. In the Zap, you can select which fields to push to the issue so we can leave email out but still collect it via Typeform. 

maptime hq start a chapter

- Here's a [video of it in action](https://cloudup.com/cI_yM4lz0CO)
- Pull [this branch](https://github.com/maptime/maptime.github.io/tree/onboarding-typeform) to take it for a spin
- Issues go [here](https://github.com/geografa/maptime-chapters/issues) for now

**Comment by geobrando** [comment]
:+1: Excellent!

Other thoughts

* Trigger an email reply to the user thanking them and telling them what the next steps are.  This is when you could encourage them to register on github and then directing them to "Issues" so they can track the progress and interact with the onboarder.  Might even be possible to send them a url to the actual issue itself.

* Send the entire form data to a private google sheet (if that's where you want to have the master record).  Onboarders can refer to that if they want to read the "Why" or email the user back for any reason.

* I would say these belong in maptime-admin instead of the starter repo, since these requests involve more then just a website, but might require decisions about if this request is approved, and then making sure they get added to the Github org, getting set up on Slack, etc.  You could create milestones for each of these steps.

**Comment by geografa** [comment]
@geobrando great ideas!

> Trigger an email reply to the user thanking them and telling them what the next steps are. 

I'd love to avoid email as much as possible. I feel it should be used sparingly. I think we can direct them straight to the issues where they can see the results and further discussion and clarifications can be made there. Imagine managing a handful of clarifications over email on a busy week :stuck_out_tongue_closed_eyes: 

> Might even be possible to send them a url to the actual issue itself.

We can do that on completion of the form as well - just a link to the issues. Note that Zaps run on 15 min intervals so there will be a delay.

> Send the entire form data to a private google sheet 

That's possible with a Zap.
create_new_zap_-_zapier

> I would say these belong in maptime-admin instead of the starter repo, since these requests involve more then just a website, but might require decisions about if this request is approved, and then making sure they get added to the Github org, getting set up on Slack, etc. You could create checkboxes for each of these steps. You would tag the issue as Chapter request.

Good call. Once I figure out how to access the Maptime repos via Zapier, this can be done. 

> Since I don't think you can assign an issue to a group of people (i.e. the onboarders), you create an onboarders team and then mention them in the issue. 

I like it. We can do this.

editor_-_zapier

**Comment by svmatthews** [comment]
@geografa feel free to update this branch with your typeform stuff - I'm going to be away the rest of the weekend, so don't worry about writing over things.

**Comment by bethschechter** [comment]
On Sat, Apr 25, 2015 at 8:43 AM, geografa <notifications@github.com> wrote:

> @geobrando <https://github.com/geobrando> great ideas!
>
> Trigger an email reply to the user thanking them and telling them what the
> next steps are.
>
> I'd love to avoid email as much as possible. I feel it should be used
> sparingly. I think we can direct them straight to the issues where they can
> see the results and further discussion and clarifications can be made
> there. Imagine managing a handful of clarifications over email on a busy
> week [image: :stuck_out_tongue_closed_eyes:]
>

I think that we can have a thank you message on the form itself, and avoid
email.


>  Might even be possible to send them a url to the actual issue itself.
>
> We can do that on completion of the form as well - just a link to the
> issues. Note that Zaps run on 15 min intervals so there will be a delay.
>

A 15-minute delay is not a problem. We can even put language in the form
submission saying that it takes some time to go through and that they
should hear from someone soon. Email hello@ if they don't get added to
respective channels within a week.


>  Send the entire form data to a private google sheet
>
> That's possible with a Zap.
> [image: create_new_zap_-_zapier]
> <https://cloud.githubusercontent.com/assets/134753/7333475/adbbdda8-eb25-11e4-8c19-e64b8d1fb6f6.png>
>
> I would say these belong in maptime-admin instead of the starter repo,
> since these requests involve more then just a website, but might require
> decisions about if this request is approved, and then making sure they get
> added to the Github org, getting set up on Slack, etc. You could create
> checkboxes for each of these steps. You would tag the issue as Chapter
> request.
>
> Good call. Once I figure out how to access the Maptime repos via Zapier,
> this can be done.
>
Agreed. Centralizing these to-dos into a single repo I hope will make it
easier to manage.


>  Since I don't think you can assign an issue to a group of people (i.e.
> the onboarders), you create an onboarders team and then mention them in the
> issue.
>
> I like it. We can do this.
>
>
> <https://cloud.githubusercontent.com/assets/134753/7333506/c6c1d0e0-eb26-11e4-8884-4bfa6e35ccbf.png>
>

THAT IS AMAZING
AMAZING
YOU GUYS ARE AWESOME! THANK YOU SO MUCH FOR DOING THIS ON A
SATURDAY!!!!!!!!!!!!!!!!



> [image: editor_-_zapier]
> <https://cloud.githubusercontent.com/assets/134753/7333506/c6c1d0e0-eb26-11e4-8884-4bfa6e35ccbf.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maptime/maptime.github.io/pull/177#issuecomment-96229993>
> .
>



-- 
@bethschechter
Maptime <http://maptime.io/> founder
ATL –> SF –> PDX

**Comment by geobrando** [comment]
@bethschechter Wife and kid are out of town, which frees up quite a bit of time. :smile: 

The main purpose of the email was just to give them a link to github issues so they could interact with us there, as you said.  Giving a link on the form confirmation/thank you page is not great because they've lost it as soon as they navigate away from the page.

What about putting the link outside of the embedded form but on the page?  We could have a message like:

>Interested in starting a Maptime chapter ?  First, check out our [chapters](http://maptime.io/chapters/) page to see if one exists in your area and our [Github issues](https://github.com/maptime/maptime-admin/issues) page for chapters that are pending.

>Then, fill out the form below and head to the Issues page to interact with us and see the status of your reguest.

I'm sure this could be written more clearly but you get the idea.

**Comment by geografa** [comment]
Great idea. I'll add the copy.

On Saturday, April 25, 2015, Brandon Knight <notifications@github.com>
wrote:

> @bethschechter <https://github.com/bethschechter> Wife and kid are out of
> town, which frees up quite a bit of time. [image: :smile:]
>
> The main purpose of the email was just to give them a link to github
> issues so they could interact with us there, as you said. Giving a link on
> the form confirmation/thank you page is not great because they've lost it
> as soon as they navigate away from the page.
>
> What about putting the link outside of the embedded form but on the page?
> We could have a message like:
>
> Interested in starting a Maptime chapter ? First, check out our chapters
> <http://maptime.io/chapters/> page to see if one exists in your area and
> our Github issues <https://github.com/maptime/maptime-admin/issues> page
> for chapters that are pending.
>
> Then, fill out the form below and head to the Issues page to interact with
> us and see the status of your reguest.
>
> I'm sure this could be written more clearly but you get the idea.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maptime/maptime.github.io/pull/177#issuecomment-96256467>
> .
>


-- 
Rafa Gutierrez
help@mapbox.com

**Comment by geobrando** [comment]
@geografa You could even direct them right to the label we're using for pending chapters so they don't have to search hard for it

https://github.com/maptime/maptime-admin/labels/repo%20request

We should get @lyzidiamond to weigh in as I head that she's "The Decider"

**Comment by geografa** [comment]
@lyzidiamond just [created a new PR](https://github.com/maptime/maptime.github.io/pull/182) based on this one just to keep things clean. See copy edits and form. I think this is ready to go live. 

@geobrando do you want to be on the onboarders team? Others?

**Comment by geobrando** [comment]
@geografa Sure!

**Comment by svmatthews** [comment]
Closing in favor of #182

**Comment by lyzidiamond** [comment]
Lyzi "The Decider" Diamond

**Comment by svmatthews** [comment]
Damnnnnn

**Comment by bethschechter** [comment]
:thumbsup:
:)

On Mon, May 4, 2015 at 3:44 PM, Sam Matthews <notifications@github.com>
wrote:

> Damnnnnn
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maptime/maptime.github.io/pull/177#issuecomment-98877118>
> .
>



-- 
@bethschechter
Maptime <http://maptime.io/> founder
ATL –> SF –> PDX

**Pull request closed without merging**
