### PR TITLE
Adds Maptime Tunisia 

### PR DESCRIPTION
**Pull request by MaptimeTN**
Hi, i want to add tunisia on the map :)
cc @geografa

### CODE REVIEW

**Comment by geobrando** [comment]
Tunisia?? Awesome!!

**Comment by MaptimeTN** [comment]
@geobrando Hopefully We can make it :+1:

**Comment by geografa** [comment]
Hey @MaptimeTN ! Excited to see you on the map. Are you requesting a repo or a chapter location on the map?

**Comment by MaptimeTN** [comment]
@geografa I am requesting both :+1:

**Comment by geobrando** [comment]
Hi @MaptimeTN 

What city or area do you plan to hold events?  It would be preferable if you narrowed it down a bit (e.g. MaptimeTunis or MaptimeSfax).

**Comment by geobrando** [comment]
@MaptimeTN ping

**Comment by MaptimeTN** [comment]
Hi, 
I would like MaptimeTunis 
thx 


     Le Mercredi 1 juillet 2015 21h10, Brandon Knight <notifications@github.com> a écrit :
   

 @MaptimeTN ping—

**Comment by geobrando** [comment]
@MaptimeTN Created a repo to manage your web page, which uses our starter template. Gave you write privileges.  

repo: https://github.com/maptime/tunis
site: http://maptime.io/tunis

You need to edit the [_config.yml](https://github.com/maptime/tunis/blob/gh-pages/_config.yml) file in the repo.  Instructions are in the readme file. Let me know if you need help editing this  file or creating posts/events.  You're also free to scrap this starter template if you prefer to build a custom web page.

I also added you to  [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json?short_path=672e323) which renders your chapter in the list and on the map at http://maptime.io/chapters.  I guessed that [this](https://twitter.com/hamed_gamaoun) was your twitter account.  If not, let me know and I can remove it.

Please post any other questions you might have in #general channel on Slack.  I'm `@brandon` there.  It would appreciated it if you would introduce yourself in the #intros channel.

Thanks!

**Pull request closed without merging**
