### PR TITLE
update MaptimeTPE twitter link

### PR DESCRIPTION
**Pull request by bdon**

### CODE REVIEW

**Comment by almccon** [comment]
hmm, this looks controversial. We better review it in front of all of maptime.

**Comment by lyzidiamond** [comment]
Boo! This is a great PR. Should be merged immediately. :grapes:

**Comment by briandaviddavidson** [comment]
:+1: This looks good to me! Let's pull it!

**Comment by powersa** [comment]
:rainbow:

**Comment by ebrelsford** [comment]
:metal:

**Comment by almccon** [comment]
whew.

**Pull request merged**
