### PR TITLE
Adding a Maptime chapter for Tallahassee

### PR DESCRIPTION
**Pull request by benjaminwthornton**
I have set up the basic index page for the Tallahassee Maptime page. Do I need to add any styling or will the css for the rest of the site work on it? Let me know if I need to fix anything. 

/cc @geografa

### CODE REVIEW

**Comment by geografa** [comment]
@benjaminwthornton We're making full repos for chapters now. If you want to stick with this static page, that's fine but let me know if you want the repo and I'll just clone the starter repo into it and set you as admin. And let me know if you have other admins in mind.

**Comment by benjaminwthornton** [comment]
Ok. I'll go with the full repo. That will be easier to work with. And I don't have any admins in mind yet but I will let you know if I find another person.

**Comment by geobrando** [comment]
@benjaminwthornton : Added a repo for you and have given you commit privileges. You can find it [here](https://github.com/maptime/tallahassee) and your site will be served [here](http://maptime.io/tallahassee/).  You'll need to customize the site by editing your [`_config.yml`](https://github.com/maptime/tallahassee/blob/gh-pages/_config.yml) as described in the [`Readme.md`](https://github.com/maptime/tallahassee/blob/gh-pages/README.md)

A few other things:

1. Want to take a stab at adding your chapter to [`chapters.json`](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json)?  If you're still in the planning stages make sure to add a `"comingSoon": true` tag.  I noticed that you have a twitter handle.  If that's the nickname of your chapter, make sure to add **MaptimeTLH** as both the `"twitter":` and `"title":` . If you need help we can take care of it for you.  

1. We find that successful chapters have multiple organizers.  If you're currently the sole organizer I would recommend trying to find at least one or two others to help you out to lessen the load.

1.  Let me know if you still need to be added to our Slack.

**Comment by benjaminwthornton** [comment]
Hi @geobrando: Thanks for the new repo. I will get working on customizing that this weekend. 

1. When it comes to the JSON, I just edited it and put the tallahassee chapter info in and pushed it to the main repo. Let me know if i need to do anything more with that.

2. I am currently the sole organizer but plan to bring someone else on in the next couple of months.

3. I am on the slack already as well and learning a lot from that. 

Thanks for all the help!

**Pull request closed without merging**
