### PR TITLE
Add Maptime Copenhagen to the chapters.json file

### PR DESCRIPTION
**Pull request by travel193**

### CODE REVIEW

**Comment by geobrando** [comment]
Hi @travel193.  Thanks for this, but there are some issues that are causing this to be invalid json.

Instead of regular quotation marks you're using the left double quotation mark character in six places, you're missing quotes around `MaptimeCPH`.  You've got extraneous commas at the end of the `"organizers"` array and the `"properties"` object and an extraneous period in the latitude. 

If you can make those changes I'll merge.  You can paste the new file into http://jsonlint.com to ensure that it's valid json. If you need help I'm happy commit your additions instead.

**Comment by travel193** [comment]
Hi @geobrando ,

My apologies. I didn't notice the left quotations. I think it's best you commit the changes. I keep getting a parsing error on line 558 and I'm not sure what is causing it.

```
{
       "type": "Feature",
       "properties": {
 	"location": "Copenhagen, Denmark",
        "title": "MaptimeCopenhagen",
     	"twitter": "MaptimeCPH",
        "website": "http://maptime.io/copenhagen/",
        "github": "https://github.com/maptime/copenhagen/",
      "organizers": [
          {
            "name": "Edoardo Neerhut",
            "twitter": "travel193"
          },
          {
            "name": "Jan Erik Solem",
            "twitter": "jesolem"
          }
        ],
        "meetup": "http://www.meetup.com/Maptime-Copenhagen/",
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          12.5683,
	55.6761
        ]
      }
    },
```

**Comment by geobrando** [comment]
@travel193 No worries. You don't need a comma after the last element in an array or member of an object.  So you just need remove the comma at the end of that line.  `"meetup": *` is the last member of your `properties` object.

Doing what you're doing is exactly how I learned to form valid json/geojson

**Comment by geobrando** [comment]
:+1:

**Comment by travel193** [comment]
Awesome. Thanks @geobrando

**Pull request merged**
