### PR TITLE
Onboarding typeform

### PR DESCRIPTION
**Pull request by geografa**

### CODE REVIEW

**Comment by svmatthews** [comment]
### Form Content

* name
* email
* personal twitter handle (optional)
* Where do you want to start a Maptime?
* When do you want to start?
* Why do you want to start a Maptime?
* Chapter twitter handle
* Organizer GH handle
* Additional organizer names (optional)

**Comment by geobrando** [comment]
Form draft: https://geografa.typeform.com/to/xQ3rk7

@svmatthews Agree with the form content

**Required**: name, email, where, why (for some quality control), when (even if it's "Not sure")

The rest should be optional at time of form submission.

### Questions:

1. Are we requiring that chapters maintain a website and are we encouraging them to host it in the Maptime Org? If not, github handle might not even be necessary.  While optional in the form they'll need one if they are hosting with us.

1. Are we requiring a twitter account?

**Comment by svmatthews** [comment]
Sorry, should have specified that those fields come from [this gist](https://gist.github.com/bethschechter/386f264a841507f87e47#file-gistfile1-md) put together by @bethschechter

**Comment by geografa** [comment]
My personal pref -  I'd like this to be as short as possible so it just gets the ball rolling. I understand the need for all the q's but wondering if this can be consolidated or simplified. Or maybe I'm just lazy :stuck_out_tongue_winking_eye: Just a personal pref.

If we're asking the 'why' question, this can be an optional comment field at the end of the form. 

@geobrando The only req fields I see are name, email (changed my mind since we can now hide this from the GH issue), and where.

**Comment by lyzidiamond** [comment]
I'm merging this now. Thanks for all the personal, in-person nudges, @geografa and @svmatthews. We can always update this as needed.

**Pull request merged**
