### PR TITLE
Adding a new Chapter for Baltimore!

### PR DESCRIPTION
**Pull request by talllguy**

### CODE REVIEW

**Comment by talllguy** [comment]
Finishing this PR will satisfy https://github.com/maptimebmore/set-up/issues/7

**Comment by geobrando** [comment]
Sorry @talllguy. We''re no longer creating chapter websites directly using maptime.github.up. We need to update those instructions. We'll be creating a Maptime/baltimore repo shortly which will serve a page at Maptime.io/baltimore

**Comment by talllguy** [comment]
@lyzidiamond get that [gist](https://gist.github.com/lyzidiamond/49626543a42d2259730e) updated then :) No problem though.

**Comment by lyzidiamond** [comment]
@talllguy on it!

**Comment by talllguy** [comment]
Deleted my fork. :no_good:

**Pull request closed without merging**
