### PR TITLE
MaptimeWLON Folder created

### PR DESCRIPTION
**Pull request by antmole**
I just created the basic page for West London - nothing fancy yet ;)

Will

### CODE REVIEW

**Comment by antmole** [comment]
Hi @geografa Have we done this correctly?

Cheers
John & Billy

**Comment by geografa** [comment]
@antmole we've just changed things up a little and are asking new chapter admins to fill out the form on our new [Chapter Start page](http://maptime.io/start/). There are just five questions at the moment and it will help us get your page up and running. A repository will be made so you and other admins can control the repo and pages yourself. Let me know what you think and if you have any troubles.

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
@geografa I see now why I was confused about this. I missed this message.  This chapter had been in existence for some time. To avoid confusion, the form should probably only be used for initial requests/inquiries.

**Comment by geografa** [comment]
:+1:

**Pull request closed without merging**
