### PR TITLE
Glossary

### PR DESCRIPTION
**Pull request by rhewitt22**
First crack at #124 

I was working on something similar at work so I thought I'd pitch that solution here.  Check out the glossary dev branch.  I grabbed the first couple of items from the ABCs wiki to use in this example.  A full implementation would include copying over the remaining terms.

Solution:
1. Maintain a list of glossary terms as a yaml file.  I like the idea of the abc's of cartography wiki, but it looks like it doesn't get as many contributions as it might as part of maptime.io.
2. Echo out those terms in a template so that they're indexed by search engines.
3. Use the same data in a JS file to allow the user to filter terms with a simple form input + jQuery magic.

I think the number of eyes and contributors on the maptime.io website might be a great resource to expand on the abcs of cartography/glossary/wiki.

### CODE REVIEW

**Comment by geobrando** [comment]
This is pretty neat @rhewitt22 and I think deserves some consideration.  Pinging @maptime/owners.

I'll see if I can grab a screenshot to post here.

**Comment by geografa** [comment]
pretty sweet @rhewitt22 . Any considerations to protocols for naming or linking out? Like, I can see if you include a definition for GeoJSON, you might want to link to the canonical source. Would we be naming images as their definition? I can add this to a CONTRIBUTING.md guide.

**Comment by rhewitt22** [comment]
I have an [updated version](http://codepen.io/rhewitt/full/KpzGOo) that gives better search results using lunr.js.  I like the off-canvas approach as it allows you to have access to the glossary on any page plus it can automatically find and highlight glossary terms throughout the site.

@geografa In order to allow linking from within a definition the field accepts an HTML string, which will render with [Handlebars escaped html](http://handlebarsjs.com/#html-escaping).  The image accepts a file path string, which could either be absolute and text for the `alt` attribute.

How about this for the documentation:
```yml
# Add a term to the glossary:
- term: (string)
  definition: (html string)
  tags: (array)
  image: (optional)
    src: Absolute path to image (string) # http://maptime.io/img/atlas.gif
    alt: For screen readers (string)
```

**Comment by rhewitt22** [comment]
Closed in favor of #235.

**Pull request closed without merging**
