### PR TITLE
New glossary

### PR DESCRIPTION
**Pull request by rhewitt22**
An update to #185 that addresses #124.

An off-canvas glossary that appears when you need it, out of site when you don't.  Glossary terms are automatically highlighted (underlined with a blue dashed line).  When clicked they toggle the glossary with the given term added to the search box.

The definition can contain HTML for linking to other sources.

Want to see it in action? Check out a quick [Screencast](http://quick.as/92omCPg1Z).

For documentation on terms in `_data/glossary.yml`:
```yml
# Add a term to the glossary:
- term: (string)
  definition: (html string)
  tags: (array)
  image: (optional)
    src: Image name (string) -- PLACE IMAGES in `/img`
    alt: For screen readers (string)
```

cc/ @geobrando @geografa

### CODE REVIEW

**Comment by rhewitt22** [comment]
@geobrando Hey didn't see you were working on this.

I swapped the anchor tag out with a span so it wouldn't error out the CI build.  I couldn't figure out how to get the menu item to have the correct background color, though.

**Comment by geobrando** [comment]
Sorry.  Should have commented on that.  I don't have a problem ignoring anchors.  Feel free to change it back to the anchors if you prefer.

**Comment by rhewitt22** [comment]
@geobrando ready for :eyes:

**Comment by geobrando** [comment]
This is really good.  Since this is a substantial addition, can we get an ok from someone in HQ?  @almccon @lyzidiamond @bethschechter @camilleanne 

@geografa So you're thinking we should add a separate CONTRIBUTING.md with the documentation?  What about right in the README? Either way is fine with me.

Once this is merged we can ask for help migrating terms from [abcs-of-cartography](https://github.com/maptime/abcs-of-cartography/wiki/Glossary)

**Comment by almccon** [comment]
Damn, the [screencast](http://quick.as/92omCPg1Z) is impressive. I haven't looked at the code in this PR, but I say go for it!

**Comment by mapsam** [comment]
:clap:

**Comment by geobrando** [comment]
Alright. Merging!

After we confirm it works as intended, I can send out a message on Slack and ask for help.  Let's def add some documentation as well.  We could just add a commented-out version of the template @rhewitt22 wrote above directly in glossary.yml.  Seems pretty straightforward.

**Comment by geografa** [comment]
Nice work @rhewitt22 :+1: . Any idea why `bathymetry` isn't working in the search? 

Down the line, it would be cool hash results so we can direct link to terms as they're bound to get linked

**Comment by rhewitt22** [comment]
Derp.

I threw the wrong name at the lunrjs index.  PR on it's way!

**Pull request merged**
