### PR TITLE
adding maptime cape cod

### PR DESCRIPTION
**Pull request by guitar1999**
Hi,
We'd like to get Maptime Cape Cod added to the map! Please let me know if there's anything else I need to do.
Thanks,
Jesse

### CODE REVIEW

**Comment by geobrando** [comment]
Looks good.  Did you want to add your website as well?

**Comment by guitar1999** [comment]
Good call! I added the website...

**Comment by geobrando** [comment]
Great. Chapter sites will redirect. Could you change to http://maptime.io/capecod/

**Comment by guitar1999** [comment]
Sorry about that. It's changed.

**Comment by geobrando** [comment]
No problem at all. Thanks!

**Pull request merged**
