### PR TITLE
adding MaptimeBmore

### PR DESCRIPTION
**Pull request by hoganmaps**
It looks like my editor beautified a few spacing things in the MSP entry, if that is alright, here is bmore.

### CODE REVIEW

**Comment by talllguy** [comment]
Thanks Chris. This will satisfy https://github.com/maptimebmore/set-up/issues/8

**Comment by hoganmaps** [comment]
:+1:

**Comment by geografa** [comment]
Looking good, Baltimore!

**Comment by talllguy** [comment]
Closes https://github.com/maptime/maptime-admin/issues/132

**Comment by talllguy** [comment]
Nice. Closes https://github.com/maptimebmore/set-up/issues/8

**Pull request merged**
